const recipe2 = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: true,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 11,
  gaps: "no",
  lowFodmap: false,
  aggregateLikes: 2,
  spoonacularScore: 92.0,
  healthScore: 90.0,
  creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
  license: "CC BY 3.0",
  sourceName: "Foodista",
  pricePerServing: 168.12,
  id: 654959,
  title: "Pasta With Tuna",
  readyInMinutes: 45,
  servings: 4,
  sourceUrl: "http://www.foodista.com/recipe/K6QWSKQM/pasta-with-tuna",
  image: "https://spoonacular.com/recipeImages/654959-312x231.jpg",
  imageType: "jpg",
  nutrition: {
    nutrients: [
      {
        name: "Calories",
        title: "Calories",
        amount: 420.82,
        unit: "kcal",
        percentOfDailyNeeds: 21.04,
      },
      {
        name: "Fat",
        title: "Fat",
        amount: 10.33,
        unit: "g",
        percentOfDailyNeeds: 15.89,
      },
      {
        name: "Saturated Fat",
        title: "Saturated Fat",
        amount: 2.35,
        unit: "g",
        percentOfDailyNeeds: 14.69,
      },
      {
        name: "Carbohydrates",
        title: "Carbohydrates",
        amount: 57.69,
        unit: "g",
        percentOfDailyNeeds: 19.23,
      },
      {
        name: "Net Carbohydrates",
        title: "Net Carbohydrates",
        amount: 52.7,
        unit: "g",
        percentOfDailyNeeds: 19.16,
      },
      {
        name: "Sugar",
        title: "Sugar",
        amount: 8.45,
        unit: "g",
        percentOfDailyNeeds: 9.39,
      },
      {
        name: "Cholesterol",
        title: "Cholesterol",
        amount: 22.37,
        unit: "mg",
        percentOfDailyNeeds: 7.46,
      },
      {
        name: "Sodium",
        title: "Sodium",
        amount: 270.71,
        unit: "mg",
        percentOfDailyNeeds: 11.77,
      },
      {
        name: "Protein",
        title: "Protein",
        amount: 24.48,
        unit: "g",
        percentOfDailyNeeds: 48.95,
      },
      {
        name: "Vitamin K",
        title: "Vitamin K",
        amount: 311.25,
        unit: "µg",
        percentOfDailyNeeds: 296.43,
      },
      {
        name: "Selenium",
        title: "Selenium",
        amount: 74.25,
        unit: "µg",
        percentOfDailyNeeds: 106.07,
      },
      {
        name: "Vitamin C",
        title: "Vitamin C",
        amount: 39.71,
        unit: "mg",
        percentOfDailyNeeds: 48.13,
      },
      {
        name: "Vitamin A",
        title: "Vitamin A",
        amount: 2021.93,
        unit: "IU",
        percentOfDailyNeeds: 40.44,
      },
      {
        name: "Manganese",
        title: "Manganese",
        amount: 0.78,
        unit: "mg",
        percentOfDailyNeeds: 38.85,
      },
      {
        name: "Phosphorus",
        title: "Phosphorus",
        amount: 354.53,
        unit: "mg",
        percentOfDailyNeeds: 35.45,
      },
      {
        name: "Vitamin B3",
        title: "Vitamin B3",
        amount: 7.04,
        unit: "mg",
        percentOfDailyNeeds: 35.18,
      },
      {
        name: "Vitamin B12",
        title: "Vitamin B12",
        amount: 1.63,
        unit: "µg",
        percentOfDailyNeeds: 27.21,
      },
      {
        name: "Calcium",
        title: "Calcium",
        amount: 236.71,
        unit: "mg",
        percentOfDailyNeeds: 23.67,
      },
      {
        name: "Folate",
        title: "Folate",
        amount: 86.5,
        unit: "µg",
        percentOfDailyNeeds: 21.63,
      },
      {
        name: "Iron",
        title: "Iron",
        amount: 3.62,
        unit: "mg",
        percentOfDailyNeeds: 20.11,
      },
      {
        name: "Fiber",
        title: "Fiber",
        amount: 5.0,
        unit: "g",
        percentOfDailyNeeds: 19.98,
      },
      {
        name: "Vitamin B2",
        title: "Vitamin B2",
        amount: 0.34,
        unit: "mg",
        percentOfDailyNeeds: 19.73,
      },
      {
        name: "Magnesium",
        title: "Magnesium",
        amount: 77.62,
        unit: "mg",
        percentOfDailyNeeds: 19.4,
      },
      {
        name: "Vitamin B6",
        title: "Vitamin B6",
        amount: 0.36,
        unit: "mg",
        percentOfDailyNeeds: 17.98,
      },
      {
        name: "Vitamin B1",
        title: "Vitamin B1",
        amount: 0.26,
        unit: "mg",
        percentOfDailyNeeds: 17.11,
      },
      {
        name: "Potassium",
        title: "Potassium",
        amount: 586.38,
        unit: "mg",
        percentOfDailyNeeds: 16.75,
      },
      {
        name: "Zinc",
        title: "Zinc",
        amount: 2.35,
        unit: "mg",
        percentOfDailyNeeds: 15.69,
      },
      {
        name: "Copper",
        title: "Copper",
        amount: 0.31,
        unit: "mg",
        percentOfDailyNeeds: 15.66,
      },
      {
        name: "Vitamin E",
        title: "Vitamin E",
        amount: 1.54,
        unit: "mg",
        percentOfDailyNeeds: 10.27,
      },
      {
        name: "Vitamin D",
        title: "Vitamin D",
        amount: 1.5,
        unit: "µg",
        percentOfDailyNeeds: 10.02,
      },
      {
        name: "Vitamin B5",
        title: "Vitamin B5",
        amount: 0.75,
        unit: "mg",
        percentOfDailyNeeds: 7.53,
      },
    ],
    properties: [
      {
        name: "Glycemic Index",
        title: "Glycemic Index",
        amount: 78.15,
        unit: "",
      },
      {
        name: "Glycemic Load",
        title: "Glycemic Load",
        amount: 22.54,
        unit: "",
      },
    ],
    flavonoids: [
      {
        name: "Cyanidin",
        title: "Cyanidin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Petunidin",
        title: "Petunidin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Delphinidin",
        title: "Delphinidin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Malvidin",
        title: "Malvidin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Pelargonidin",
        title: "Pelargonidin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Peonidin",
        title: "Peonidin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Catechin",
        title: "Catechin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epigallocatechin",
        title: "Epigallocatechin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epicatechin",
        title: "Epicatechin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epicatechin 3-gallate",
        title: "Epicatechin 3-gallate",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epigallocatechin 3-gallate",
        title: "Epigallocatechin 3-gallate",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Theaflavin",
        title: "Theaflavin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Thearubigins",
        title: "Thearubigins",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Eriodictyol",
        title: "Eriodictyol",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Hesperetin",
        title: "Hesperetin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Naringenin",
        title: "Naringenin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Apigenin",
        title: "Apigenin",
        amount: 32.33,
        unit: "mg",
      },
      {
        name: "Luteolin",
        title: "Luteolin",
        amount: 0.17,
        unit: "mg",
      },
      {
        name: "Isorhamnetin",
        title: "Isorhamnetin",
        amount: 0.25,
        unit: "mg",
      },
      {
        name: "Kaempferol",
        title: "Kaempferol",
        amount: 0.6,
        unit: "mg",
      },
      {
        name: "Myricetin",
        title: "Myricetin",
        amount: 2.23,
        unit: "mg",
      },
      {
        name: "Quercetin",
        title: "Quercetin",
        amount: 3.73,
        unit: "mg",
      },
      {
        name: "Theaflavin-3,3'-digallate",
        title: "Theaflavin-3,3'-digallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Theaflavin-3'-gallate",
        title: "Theaflavin-3'-gallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Theaflavin-3-gallate",
        title: "Theaflavin-3-gallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Gallocatechin",
        title: "Gallocatechin",
        amount: 0.0,
        unit: "mg",
      },
    ],
    ingredients: [
      {
        id: 20081,
        name: "flour",
        amount: 0.5,
        unit: "tablespoons",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 0.56,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 5.78,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.17,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 0.39,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.1,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.22,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 6.86,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.39,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 2.86,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.04,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 2.76,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 0.83,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 1.27,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 13.65,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.0,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 4.05,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 0.08,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.01,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 4.01,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.0,
            unit: "mg",
          },
        ],
      },
      {
        id: 11291,
        name: "green onions",
        amount: 0.25,
        unit: "cup",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 18.0,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.1,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.58,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.37,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 1.43,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.65,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 4.7,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.13,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 16.0,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.14,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.46,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 1.84,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.05,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 1.19,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.04,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 5.0,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.15,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 8.0,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 249.25,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 9.25,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 4.0,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 51.75,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 69.0,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.02,
            unit: "mg",
          },
        ],
      },
      {
        id: 1085,
        name: "non-fat milk",
        amount: 0.31,
        unit: "cups",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 93.41,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.32,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 3.9,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 11.94,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.07,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 3.83,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 2.58,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 3.8,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.06,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 3.8,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.27,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 8.42,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.92,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.04,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 2.37,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.14,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 26.03,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.38,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 156.19,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 77.33,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 32.16,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Fluoride",
            name: "Fluoride",
            amount: 2.37,
            unit: "mg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 119.44,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 1.53,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.03,
            unit: "mg",
          },
        ],
      },
      {
        id: 4053,
        name: "olive oil",
        amount: 0.5,
        unit: "tablespoons",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 0.07,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.04,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 5.11,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 1.0,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 7.0,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.74,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.97,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 61.88,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.0,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 0.14,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 4.21,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 0.07,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.0,
            unit: "mg",
          },
        ],
      },
      {
        id: 11282,
        name: "onion",
        amount: 0.5,
        unit: "tablespoons",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 1.15,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.21,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 0.31,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.09,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.37,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 0.95,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.06,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.47,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.38,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 0.5,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.03,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 2.0,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.1,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 1.45,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 0.2,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.02,
            unit: "µg",
          },
          {
            title: "Fluoride",
            name: "Fluoride",
            amount: 0.06,
            unit: "mg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 7.3,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.01,
            unit: "mg",
          },
        ],
      },
      {
        id: 1033,
        name: "parmesan cheese",
        amount: 0.06,
        unit: "cup",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 74.0,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.17,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.05,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.05,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.47,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 0.96,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 0.44,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 2.23,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.2,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 1.61,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.2,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.04,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 2.75,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.03,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 1.03,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 1.41,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 24.5,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.08,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 48.81,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 43.38,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 100.13,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.11,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 5.75,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 4.25,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.01,
            unit: "mg",
          },
        ],
      },
      {
        id: 11297,
        name: "parsley",
        amount: 0.25,
        unit: "cup",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 20.7,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.16,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.13,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.93,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.04,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 1.92,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.5,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 19.95,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.2,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 22.8,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.11,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.45,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.95,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.12,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.45,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.06,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 7.5,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.02,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 5.4,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 1263.6,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 8.7,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 8.4,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 246.0,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 83.1,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.01,
            unit: "mg",
          },
        ],
      },
      {
        id: 20420,
        name: "pasta",
        amount: 2.0,
        unit: "ounces",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 11.91,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.16,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.8,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 1.51,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.74,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.1,
            unit: "g",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 1.81,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.96,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 10.21,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.06,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 7.39,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 42.34,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.86,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 40.52,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.24,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.32,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.52,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 30.05,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.16,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 35.83,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 210.35,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Trans Fat",
            name: "Trans Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.0,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 107.16,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 3.4,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.06,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 126.44,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.05,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.08,
            unit: "mg",
          },
        ],
      },
      {
        id: 11304,
        name: "peas",
        amount: 0.25,
        unit: "cup",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 9.06,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.06,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.45,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 2.06,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.53,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 10.3,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 1.85,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 14.5,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.76,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 23.56,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.05,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 1.96,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 5.24,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.14,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 3.39,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.04,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.07,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.15,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 11.96,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.03,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.65,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.05,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 29.36,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 277.31,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 39.15,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 1.81,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 8.99,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 88.45,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.1,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.06,
            unit: "mg",
          },
        ],
      },
      {
        id: 6168,
        name: "pepper sauce",
        amount: 0.25,
        unit: "",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.19,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 0.02,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 0.03,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.41,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 6.61,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.01,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 0.36,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.0,
            unit: "mg",
          },
        ],
      },
      {
        id: 15121,
        name: "water-packed tuna",
        amount: 1.63,
        unit: "ounces",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 7.83,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.32,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.75,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.05,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 13.5,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 4.67,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 1.84,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.15,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 8.96,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.44,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.07,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.13,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 10.6,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.55,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.1,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 32.52,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.04,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 39.62,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 1.17,
            unit: "µg",
          },
          {
            title: "Trans Fat",
            name: "Trans Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 26.26,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 64.03,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 113.79,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.09,
            unit: "µg",
          },
          {
            title: "Fluoride",
            name: "Fluoride",
            amount: 8.57,
            unit: "mg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 82.46,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 16.58,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.15,
            unit: "mg",
          },
        ],
      },
    ],
    caloricBreakdown: {
      percentProtein: 23.22,
      percentFat: 22.05,
      percentCarbs: 54.73,
    },
    weightPerServing: {
      amount: 278,
      unit: "g",
    },
  },
  summary:
    'Pasta With Tuna might be just the main course you are searching for. One serving contains <b>421 calories</b>, <b>24g of protein</b>, and <b>10g of fat</b>. For <b>$1.68 per serving</b>, this recipe <b>covers 28%</b> of your daily requirements of vitamins and minerals. 1 person were impressed by this recipe. Head to the store and pick up flour, onion, peas, and a few other things to make it today. It is a good option if you\'re following a <b>pescatarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 92%</b>. This score is excellent. Try <a href="https://spoonacular.com/recipes/pasta-and-tuna-salad-ensalada-de-pasta-y-atn-226303">Pastan and Tuna Salad (Ensalada de Pasta y Atún)</a>, <a href="https://spoonacular.com/recipes/tuna-pasta-565100">Tuna Pasta</a>, and <a href="https://spoonacular.com/recipes/tuna-pasta-89136">Tuna Pasta</a> for similar recipes.',
  cuisines: [],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: ["pescatarian"],
  occasions: [],
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Cook pasta in a large pot of boiling water until al dente.",
          ingredients: [
            {
              id: 20420,
              name: "pasta",
              localizedName: "pasta",
              image: "fusilli.jpg",
            },
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
          ],
          equipment: [
            {
              id: 404752,
              name: "pot",
              localizedName: "pot",
              image: "stock-pot.jpg",
            },
          ],
        },
        {
          number: 2,
          step: "Drain and return to warm pot. Put olive oil in saucepan and add onion.",
          ingredients: [
            {
              id: 4053,
              name: "olive oil",
              localizedName: "olive oil",
              image: "olive-oil.jpg",
            },
            {
              id: 11282,
              name: "onion",
              localizedName: "onion",
              image: "brown-onion.png",
            },
          ],
          equipment: [
            {
              id: 404669,
              name: "sauce pan",
              localizedName: "sauce pan",
              image: "sauce-pan.jpg",
            },
            {
              id: 404752,
              name: "pot",
              localizedName: "pot",
              image: "stock-pot.jpg",
            },
          ],
        },
        {
          number: 3,
          step: "Saute until transparent. Stir in flour and cook for a few seconds and then whisk in milk. Stir constantly until this thickens.",
          ingredients: [
            {
              id: 20081,
              name: "all purpose flour",
              localizedName: "all purpose flour",
              image: "flour.png",
            },
            {
              id: 1077,
              name: "milk",
              localizedName: "milk",
              image: "milk.png",
            },
          ],
          equipment: [
            {
              id: 404661,
              name: "whisk",
              localizedName: "whisk",
              image: "whisk.png",
            },
          ],
        },
        {
          number: 4,
          step: "Add peas, tuna (shredded into chunks,) parsley, green onions, cheese and hot pepper sauce.",
          ingredients: [
            {
              id: 6168,
              name: "hot sauce",
              localizedName: "hot sauce",
              image: "hot-sauce-or-tabasco.png",
            },
            {
              id: 11291,
              name: "green onions",
              localizedName: "green onions",
              image: "spring-onions.jpg",
            },
            {
              id: 11297,
              name: "parsley",
              localizedName: "parsley",
              image: "parsley.jpg",
            },
            {
              id: 1041009,
              name: "cheese",
              localizedName: "cheese",
              image: "cheddar-cheese.png",
            },
            {
              id: 11304,
              name: "peas",
              localizedName: "peas",
              image: "peas.jpg",
            },
            {
              id: 10015121,
              name: "tuna",
              localizedName: "tuna",
              image: "canned-tuna.png",
            },
          ],
          equipment: [],
        },
        {
          number: 5,
          step: "Pour over pasta and stir gently to mix.",
          ingredients: [
            {
              id: 20420,
              name: "pasta",
              localizedName: "pasta",
              image: "fusilli.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 6,
          step: "Serve at once.",
          ingredients: [],
          equipment: [],
        },
      ],
    },
  ],
  spoonacularSourceUrl: "https://spoonacular.com/pasta-with-tuna-654959",
};
export default recipe2;
