const recipe3 = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 24,
  gaps: "no",
  lowFodmap: false,
  aggregateLikes: 1,
  spoonacularScore: 67.0,
  healthScore: 28.0,
  creditsText: "Pick Fresh Foods",
  license: "CC BY 3.0",
  sourceName: "Pick Fresh Foods",
  pricePerServing: 274.82,
  id: 511728,
  title: "Pasta Margherita",
  readyInMinutes: 45,
  servings: 4,
  sourceUrl: "http://pickfreshfoods.com/pasta-margherita/",
  image: "https://spoonacular.com/recipeImages/511728-312x231.jpg",
  imageType: "jpg",
  nutrition: {
    nutrients: [
      {
        name: "Calories",
        title: "Calories",
        amount: 809.41,
        unit: "kcal",
        percentOfDailyNeeds: 40.47,
      },
      {
        name: "Fat",
        title: "Fat",
        amount: 34.38,
        unit: "g",
        percentOfDailyNeeds: 52.89,
      },
      {
        name: "Saturated Fat",
        title: "Saturated Fat",
        amount: 13.38,
        unit: "g",
        percentOfDailyNeeds: 83.66,
      },
      {
        name: "Carbohydrates",
        title: "Carbohydrates",
        amount: 89.58,
        unit: "g",
        percentOfDailyNeeds: 29.86,
      },
      {
        name: "Net Carbohydrates",
        title: "Net Carbohydrates",
        amount: 85.06,
        unit: "g",
        percentOfDailyNeeds: 30.93,
      },
      {
        name: "Sugar",
        title: "Sugar",
        amount: 5.78,
        unit: "g",
        percentOfDailyNeeds: 6.42,
      },
      {
        name: "Cholesterol",
        title: "Cholesterol",
        amount: 67.19,
        unit: "mg",
        percentOfDailyNeeds: 22.4,
      },
      {
        name: "Sodium",
        title: "Sodium",
        amount: 834.74,
        unit: "mg",
        percentOfDailyNeeds: 36.29,
      },
      {
        name: "Protein",
        title: "Protein",
        amount: 34.36,
        unit: "g",
        percentOfDailyNeeds: 68.72,
      },
      {
        name: "Selenium",
        title: "Selenium",
        amount: 86.24,
        unit: "µg",
        percentOfDailyNeeds: 123.2,
      },
      {
        name: "Manganese",
        title: "Manganese",
        amount: 1.18,
        unit: "mg",
        percentOfDailyNeeds: 58.83,
      },
      {
        name: "Phosphorus",
        title: "Phosphorus",
        amount: 534.39,
        unit: "mg",
        percentOfDailyNeeds: 53.44,
      },
      {
        name: "Calcium",
        title: "Calcium",
        amount: 464.72,
        unit: "mg",
        percentOfDailyNeeds: 46.47,
      },
      {
        name: "Vitamin B12",
        title: "Vitamin B12",
        amount: 1.94,
        unit: "µg",
        percentOfDailyNeeds: 32.32,
      },
      {
        name: "Zinc",
        title: "Zinc",
        amount: 4.22,
        unit: "mg",
        percentOfDailyNeeds: 28.16,
      },
      {
        name: "Vitamin A",
        title: "Vitamin A",
        amount: 1244.5,
        unit: "IU",
        percentOfDailyNeeds: 24.89,
      },
      {
        name: "Magnesium",
        title: "Magnesium",
        amount: 86.06,
        unit: "mg",
        percentOfDailyNeeds: 21.52,
      },
      {
        name: "Vitamin K",
        title: "Vitamin K",
        amount: 22.03,
        unit: "µg",
        percentOfDailyNeeds: 20.98,
      },
      {
        name: "Copper",
        title: "Copper",
        amount: 0.39,
        unit: "mg",
        percentOfDailyNeeds: 19.36,
      },
      {
        name: "Vitamin B2",
        title: "Vitamin B2",
        amount: 0.32,
        unit: "mg",
        percentOfDailyNeeds: 19.07,
      },
      {
        name: "Fiber",
        title: "Fiber",
        amount: 4.52,
        unit: "g",
        percentOfDailyNeeds: 18.08,
      },
      {
        name: "Vitamin E",
        title: "Vitamin E",
        amount: 2.62,
        unit: "mg",
        percentOfDailyNeeds: 17.46,
      },
      {
        name: "Potassium",
        title: "Potassium",
        amount: 493.11,
        unit: "mg",
        percentOfDailyNeeds: 14.09,
      },
      {
        name: "Vitamin B6",
        title: "Vitamin B6",
        amount: 0.26,
        unit: "mg",
        percentOfDailyNeeds: 13.04,
      },
      {
        name: "Vitamin C",
        title: "Vitamin C",
        amount: 10.21,
        unit: "mg",
        percentOfDailyNeeds: 12.38,
      },
      {
        name: "Vitamin B3",
        title: "Vitamin B3",
        amount: 2.46,
        unit: "mg",
        percentOfDailyNeeds: 12.28,
      },
      {
        name: "Iron",
        title: "Iron",
        amount: 2.18,
        unit: "mg",
        percentOfDailyNeeds: 12.1,
      },
      {
        name: "Vitamin B1",
        title: "Vitamin B1",
        amount: 0.16,
        unit: "mg",
        percentOfDailyNeeds: 10.39,
      },
      {
        name: "Folate",
        title: "Folate",
        amount: 38.04,
        unit: "µg",
        percentOfDailyNeeds: 9.51,
      },
      {
        name: "Vitamin B5",
        title: "Vitamin B5",
        amount: 0.68,
        unit: "mg",
        percentOfDailyNeeds: 6.79,
      },
      {
        name: "Vitamin D",
        title: "Vitamin D",
        amount: 0.34,
        unit: "µg",
        percentOfDailyNeeds: 2.27,
      },
    ],
    properties: [
      {
        name: "Glycemic Index",
        title: "Glycemic Index",
        amount: 51.75,
        unit: "",
      },
      {
        name: "Glycemic Load",
        title: "Glycemic Load",
        amount: 35.35,
        unit: "",
      },
    ],
    flavonoids: [
      {
        name: "Cyanidin",
        title: "Cyanidin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Petunidin",
        title: "Petunidin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Delphinidin",
        title: "Delphinidin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Malvidin",
        title: "Malvidin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Pelargonidin",
        title: "Pelargonidin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Peonidin",
        title: "Peonidin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Catechin",
        title: "Catechin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epigallocatechin",
        title: "Epigallocatechin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epicatechin",
        title: "Epicatechin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epicatechin 3-gallate",
        title: "Epicatechin 3-gallate",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epigallocatechin 3-gallate",
        title: "Epigallocatechin 3-gallate",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Theaflavin",
        title: "Theaflavin",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Thearubigins",
        title: "Thearubigins",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Eriodictyol",
        title: "Eriodictyol",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Hesperetin",
        title: "Hesperetin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Naringenin",
        title: "Naringenin",
        amount: 0.48,
        unit: "mg",
      },
      {
        name: "Apigenin",
        title: "Apigenin",
        amount: 0.01,
        unit: "mg",
      },
      {
        name: "Luteolin",
        title: "Luteolin",
        amount: 0.02,
        unit: "mg",
      },
      {
        name: "Isorhamnetin",
        title: "Isorhamnetin",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Kaempferol",
        title: "Kaempferol",
        amount: 0.07,
        unit: "mg",
      },
      {
        name: "Myricetin",
        title: "Myricetin",
        amount: 0.1,
        unit: "mg",
      },
      {
        name: "Quercetin",
        title: "Quercetin",
        amount: 0.42,
        unit: "mg",
      },
      {
        name: "Theaflavin-3,3'-digallate",
        title: "Theaflavin-3,3'-digallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Theaflavin-3'-gallate",
        title: "Theaflavin-3'-gallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Theaflavin-3-gallate",
        title: "Theaflavin-3-gallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Gallocatechin",
        title: "Gallocatechin",
        amount: 0.0,
        unit: "mg",
      },
    ],
    ingredients: [
      {
        id: 2044,
        name: "fresh basil",
        amount: 0.06,
        unit: "cup",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 2.66,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.05,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 0.17,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.27,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 1.02,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.05,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.04,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 0.96,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 0.35,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 79.13,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 0.84,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 0.06,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 6.22,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 4.43,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.0,
            unit: "mg",
          },
        ],
      },
      {
        id: 1026,
        name: "fresh mozzarella cheese",
        amount: 3.0,
        unit: "ounces",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 429.49,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 2.48,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.88,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.37,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 5.59,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 13.1,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.09,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 5.95,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.16,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 18.86,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 1.86,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 19.01,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 1.86,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.12,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.65,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 17.01,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.34,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 11.19,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 14.46,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.24,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 255.15,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 1.94,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 574.93,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 301.07,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 533.25,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 1.96,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 64.64,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 67.19,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.03,
            unit: "mg",
          },
        ],
      },
      {
        id: 11215,
        name: "garlic clove",
        amount: 0.25,
        unit: "",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 1.36,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.01,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 0.17,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.23,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 0.02,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.05,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.25,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.23,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 0.19,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.11,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 1.12,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.07,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 1.15,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 0.13,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.01,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 3.01,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.01,
            unit: "mg",
          },
        ],
      },
      {
        id: 10111529,
        name: "grape tomatoes",
        amount: 2.5,
        unit: "oz",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 7.09,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.04,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.12,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 1.86,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.19,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 4.75,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.85,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 9.71,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.42,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 10.63,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.38,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.62,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 2.76,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.14,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 1.91,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.06,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.06,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.08,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 7.8,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.02,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 12.76,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 590.38,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 17.01,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 3.54,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 5.6,
            unit: "µg",
          },
          {
            title: "Fluoride",
            name: "Fluoride",
            amount: 1.63,
            unit: "mg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 167.97,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.03,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.06,
            unit: "mg",
          },
        ],
      },
      {
        id: 1082047,
        name: "kosher salt",
        amount: 0.13,
        unit: "tsp",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 0.18,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 0.01,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 0.0,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.0,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 290.69,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Fluoride",
            name: "Fluoride",
            amount: 0.02,
            unit: "mg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 0.06,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.0,
            unit: "mg",
          },
        ],
      },
      {
        id: 4053,
        name: "olive oil",
        amount: 0.06,
        unit: "cup",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 0.14,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Caffeine",
            name: "Caffeine",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 0.08,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 9.85,
            unit: "g",
          },
          {
            title: "Choline",
            name: "Choline",
            amount: 0.04,
            unit: "mg",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 1.94,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 13.5,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 1.42,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 1.86,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 119.34,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.0,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 0.27,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 8.13,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 0.14,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.0,
            unit: "mg",
          },
        ],
      },
      {
        id: 20420,
        name: "pasta",
        amount: 0.25,
        unit: "pound",
        nutrients: [
          {
            title: "Calcium",
            name: "Calcium",
            amount: 23.81,
            unit: "mg",
          },
          {
            title: "Copper",
            name: "Copper",
            amount: 0.33,
            unit: "mg",
          },
          {
            title: "Zinc",
            name: "Zinc",
            amount: 1.6,
            unit: "mg",
          },
          {
            title: "Folic Acid",
            name: "Folic Acid",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Sugar",
            name: "Sugar",
            amount: 3.03,
            unit: "g",
          },
          {
            title: "Iron",
            name: "Iron",
            amount: 1.47,
            unit: "mg",
          },
          {
            title: "Mono Unsaturated Fat",
            name: "Mono Unsaturated Fat",
            amount: 0.19,
            unit: "g",
          },
          {
            title: "Fiber",
            name: "Fiber",
            amount: 3.63,
            unit: "g",
          },
          {
            title: "Vitamin C",
            name: "Vitamin C",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B3",
            name: "Vitamin B3",
            amount: 1.93,
            unit: "mg",
          },
          {
            title: "Folate",
            name: "Folate",
            amount: 20.41,
            unit: "µg",
          },
          {
            title: "Vitamin E",
            name: "Vitamin E",
            amount: 0.12,
            unit: "mg",
          },
          {
            title: "Protein",
            name: "Protein",
            amount: 14.79,
            unit: "g",
          },
          {
            title: "Carbohydrates",
            name: "Carbohydrates",
            amount: 84.67,
            unit: "g",
          },
          {
            title: "Fat",
            name: "Fat",
            amount: 1.71,
            unit: "g",
          },
          {
            title: "Net Carbohydrates",
            name: "Net Carbohydrates",
            amount: 81.05,
            unit: "g",
          },
          {
            title: "Vitamin B5",
            name: "Vitamin B5",
            amount: 0.49,
            unit: "mg",
          },
          {
            title: "Poly Unsaturated Fat",
            name: "Poly Unsaturated Fat",
            amount: 0.64,
            unit: "g",
          },
          {
            title: "Manganese",
            name: "Manganese",
            amount: 1.04,
            unit: "mg",
          },
          {
            title: "Magnesium",
            name: "Magnesium",
            amount: 60.1,
            unit: "mg",
          },
          {
            title: "Vitamin D",
            name: "Vitamin D",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Saturated Fat",
            name: "Saturated Fat",
            amount: 0.31,
            unit: "g",
          },
          {
            title: "Selenium",
            name: "Selenium",
            amount: 71.67,
            unit: "µg",
          },
          {
            title: "Vitamin B2",
            name: "Vitamin B2",
            amount: 0.07,
            unit: "mg",
          },
          {
            title: "Calories",
            name: "Calories",
            amount: 420.71,
            unit: "kcal",
          },
          {
            title: "Vitamin B12",
            name: "Vitamin B12",
            amount: 0.0,
            unit: "µg",
          },
          {
            title: "Trans Fat",
            name: "Trans Fat",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Alcohol",
            name: "Alcohol",
            amount: 0.0,
            unit: "g",
          },
          {
            title: "Vitamin A",
            name: "Vitamin A",
            amount: 0.0,
            unit: "IU",
          },
          {
            title: "Phosphorus",
            name: "Phosphorus",
            amount: 214.32,
            unit: "mg",
          },
          {
            title: "Sodium",
            name: "Sodium",
            amount: 6.8,
            unit: "mg",
          },
          {
            title: "Vitamin K",
            name: "Vitamin K",
            amount: 0.11,
            unit: "µg",
          },
          {
            title: "Potassium",
            name: "Potassium",
            amount: 252.88,
            unit: "mg",
          },
          {
            title: "Cholesterol",
            name: "Cholesterol",
            amount: 0.0,
            unit: "mg",
          },
          {
            title: "Vitamin B1",
            name: "Vitamin B1",
            amount: 0.1,
            unit: "mg",
          },
          {
            title: "Vitamin B6",
            name: "Vitamin B6",
            amount: 0.16,
            unit: "mg",
          },
        ],
      },
    ],
    caloricBreakdown: {
      percentProtein: 17.07,
      percentFat: 38.43,
      percentCarbs: 44.5,
    },
    weightPerServing: {
      amount: 286,
      unit: "g",
    },
  },
  summary:
    'Pasta Margherita might be just the main course you are searching for. One serving contains <b>809 calories</b>, <b>34g of protein</b>, and <b>34g of fat</b>. This recipe serves 4 and costs $2.75 per serving. 1 person has made this recipe and would make it again. If you have basil, linguine pasta, garlic clove, and a few other ingredients on hand, you can make it. To use up the olive oil you could follow this main course with the <a href="https://spoonacular.com/recipes/sauteed-banana-granola-and-yogurt-parfait-624619">Sauteed Banana, Granolan and Yogurt Parfait</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 69%</b>. This score is pretty good. Similar recipes include <a href="https://spoonacular.com/recipes/margherita-pizza-with-pesto-pasta-salad-31919">Margherita Pizza With Pesto Pasta Salad</a>, <a href="https://spoonacular.com/recipes/pasta-margherita-with-rhubarb-and-apple-compote-613006">Pasta margherita with rhubarb and apple compote</a>, and <a href="https://spoonacular.com/recipes/margherita-pizzette-516272">Margherita Pizzette</a>.',
  cuisines: [],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: [],
  occasions: [],
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Whisk oil, garlic, basil, salt together in large bowl.",
          ingredients: [
            {
              id: 11215,
              name: "garlic",
              localizedName: "garlic",
              image: "garlic.png",
            },
            {
              id: 2044,
              name: "basil",
              localizedName: "basil",
              image: "basil.jpg",
            },
            {
              id: 2047,
              name: "salt",
              localizedName: "salt",
              image: "salt.jpg",
            },
            {
              id: 4582,
              name: "cooking oil",
              localizedName: "cooking oil",
              image: "vegetable-oil.jpg",
            },
          ],
          equipment: [
            {
              id: 404661,
              name: "whisk",
              localizedName: "whisk",
              image: "whisk.png",
            },
            {
              id: 404783,
              name: "bowl",
              localizedName: "bowl",
              image: "bowl.jpg",
            },
          ],
        },
        {
          number: 2,
          step: "Add tomatoes and mozzarella then gently toss to combine; set aside.Cook pasta according to package directions for al dente.",
          ingredients: [
            {
              id: 1026,
              name: "mozzarella",
              localizedName: "mozzarella",
              image: "mozzarella.png",
            },
            {
              id: 11529,
              name: "tomato",
              localizedName: "tomato",
              image: "tomato.png",
            },
            {
              id: 20420,
              name: "pasta",
              localizedName: "pasta",
              image: "fusilli.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 3,
          step: "Drain well.",
          ingredients: [],
          equipment: [],
        },
        {
          number: 4,
          step: "Add pasta to tomato mixture and gently toss to combine.",
          ingredients: [
            {
              id: 11529,
              name: "tomato",
              localizedName: "tomato",
              image: "tomato.png",
            },
            {
              id: 20420,
              name: "pasta",
              localizedName: "pasta",
              image: "fusilli.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 5,
          step: "Serve immediately.",
          ingredients: [],
          equipment: [],
        },
      ],
    },
  ],
  spoonacularSourceUrl: "https://spoonacular.com/pasta-margherita-511728",
};
export default recipe3;
